### ISSUE TITLE
secretOrPrivateKey must have a value

### ISSUE THREAD

**Issue by sid3345** [devat-youtuber/mern-ecommerce#2]
Getting this error: **secretOrPrivateKey must have a value**.
Created .env file but what should be the contents in it ??
Unable to resolve this even after trying for long time!

![image](https://user-images.githubusercontent.com/19595612/111822443-cf444180-8909-11eb-82e1-331ee0b7273f.png)

**Comment by RekhilAlias** [comment]
open your project .env file or create

write down
MONGODB_URL = " your mongodb "
ACCESS_TOKEN_SECRET = "your token"  
REFRESH_TOKEN_SECRET = " your token'  

(https://passwordsgenerator.net/  you can generate access and refresh token)

save it  it will work

for more information watch his  video Timestamp 49.00

**Comment by devat-youtuber** [comment]
You can watch the final video deploy heroku to see the .env file
