### ISSUE TITLE
Demo page not working .

### ISSUE THREAD

**Issue by vishutiwari99** [devat-youtuber/mern-ecommerce#4]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command.

**Comment by devat-youtuber** [comment]
> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command.

**Comment by devat-youtuber** [comment]
It's correct. Heroku only gives 1000 hours / month of free use. Next month,
it will have 1000 hours for free and will function normally.

Vào Th 6, 30 thg 4, 2021 vào lúc 18:43 Vaibhav Tiwari <
***@***.***> đã viết:

**Comment by devat-youtuber** [comment]
It's correct. Heroku only gives 1000 hours / month of free use. Next month, it will have 1000 hours for free and will function normally.
